/* SESSION TYPES */
const ACTIVITY = "ACTIVITY";
const COURSE = "COURSE";
const EVENT = "EVENT";
/* ROUTE SETTINGS */
const PAGELENGTH = 6;
const MAXAGE = 400000;
module.exports = {
  /* SESSION TYPES */
  ACTIVITY,
  COURSE,
  EVENT,
  /* ROUTE SETTINGS */
  PAGELENGTH,
  MAXAGE,
};
